Fixes

diff --git a/script/install b/script/install
--- a/script/install
+++ b/script/install
@@ -9,5 +9,5 @@ cd "$(dirname "$0")"/..
 # find the installers and run them iteratively
 git ls-tree --name-only -r HEAD | grep install.sh | while read -r installer; do
 	echo "› ${installer}..."
-	sh -c "$installer"
+	sh -c "$installer" || echo "› ${installer} failed"
 done
